'use client';
import { useMemo, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { Calculator, CheckCircle2, Info } from 'lucide-react';

const models=[
  {slug:'information-led-board',name:'안내전광판',unitPrice:2070000,width:.96,height:.96,image:'/oic/prod-notice.jpg'},
  {slug:'video-wall',name:'멀티비전',unitPrice:3850000,width:1.21,height:.68,image:'/oic/prod-multivision.jpg'},
  {slug:'outdoor-kiosk',name:'옥외용 키오스크',unitPrice:9900000,width:.75,height:1.8,image:'/oic-outdoor-kiosk.jpg'},
];
const money=(value:number)=>new Intl.NumberFormat('ko-KR').format(Math.round(value));

export default function SimulatorPage(){
  const [modelSlug,setModelSlug]=useState(models[0].slug); const [wallWidth,setWallWidth]=useState(4); const [wallHeight,setWallHeight]=useState(2.5); const [columns,setColumns]=useState(3); const [rows,setRows]=useState(2);
  const model=models.find(v=>v.slug===modelSlug)??models[0];
  const result=useMemo(()=>{const quantity=Math.max(1,columns)*Math.max(1,rows);const productTotal=model.unitPrice*quantity;const fee=productTotal*.0054;const displayWidth=model.width*Math.max(1,columns);const displayHeight=model.height*Math.max(1,rows);return{quantity,productTotal,fee,total:productTotal+fee,displayWidth,displayHeight,fits:displayWidth<=wallWidth&&displayHeight<=wallHeight};},[model,columns,rows,wallWidth,wallHeight]);
  return <main className="simulator-page"><section className="simulator-hero"><p className="eyebrow light">DISPLAY ESTIMATOR</p><h1>벽면 크기와 구성을 입력해<br/>예상 금액을 확인하세요.</h1><p>설치 전 초기 검토를 돕는 참고용 계산입니다. 현장 조건과 선택 사양에 따라 최종 견적은 달라집니다.</p></section><section className="simulator-workspace"><div className="simulator-controls"><h2>1. 설치 조건 입력</h2><div className="simulator-fields"><label>벽면 가로 (m)<input type="number" min="0.5" step="0.1" value={wallWidth} onChange={e=>setWallWidth(Number(e.target.value))}/></label><label>벽면 세로 (m)<input type="number" min="0.5" step="0.1" value={wallHeight} onChange={e=>setWallHeight(Number(e.target.value))}/></label><label className="wide">제품 모델<select value={modelSlug} onChange={e=>setModelSlug(e.target.value)}>{models.map(v=><option value={v.slug} key={v.slug}>{v.name} · 시안 기준 {money(v.unitPrice)}원부터</option>)}</select></label><label>가로 수량 (열)<input type="number" min="1" max="20" value={columns} onChange={e=>setColumns(Number(e.target.value))}/></label><label>세로 수량 (단)<input type="number" min="1" max="20" value={rows} onChange={e=>setRows(Number(e.target.value))}/></label></div><div className={`fit-check ${result.fits?'fits':'over'}`}>{result.fits?<CheckCircle2/>:<Info/>}<span><b>{result.displayWidth.toFixed(2)}m × {result.displayHeight.toFixed(2)}m</b>{result.fits?'현재 입력한 벽면 안에 배치 가능한 크기입니다.':'현재 입력한 벽면보다 큽니다. 수량이나 모델을 조정해 주세요.'}</span></div></div><div className="simulator-preview"><div className="wall-preview" style={{aspectRatio:`${Math.max(wallWidth,.5)} / ${Math.max(wallHeight,.5)}`}}><div className="display-preview" style={{width:`${Math.min(100,result.displayWidth/Math.max(wallWidth,.5)*100)}%`,height:`${Math.min(100,result.displayHeight/Math.max(wallHeight,.5)*100)}%`,gridTemplateColumns:`repeat(${Math.max(1,columns)},1fr)`}}>{Array.from({length:Math.min(result.quantity,100)}).map((_,i)=><Image unoptimized width={240} height={160} key={i} src={model.image} alt=""/>)}</div></div><small>벽면 {wallWidth || 0}m × {wallHeight || 0}m · {model.name} {rows}단 {columns}열</small></div></section><section className="estimate-card"><div className="estimate-title"><Calculator/><div><p>예상 금액</p><h2>{money(result.total)}원</h2></div></div><dl><div><dt>제품 단가</dt><dd>{money(model.unitPrice)}원 × {result.quantity}대</dd></div><div><dt>제품 금액</dt><dd>{money(result.productTotal)}원</dd></div><div><dt>조달수수료 0.54%</dt><dd>{money(result.fee)}원</dd></div><div className="estimate-total"><dt>예상 합계</dt><dd>{money(result.total)}원</dd></div></dl><p><Info/> 현재 등록된 시안 기준 시작가로 계산한 참고 금액이며, 부가세·설치 구조물·전기 및 통신 공사·운송비 등은 포함되지 않을 수 있습니다.</p><Link href={`/inquiry?product=${model.slug}&columns=${columns}&rows=${rows}`}>이 구성으로 정확한 견적 문의</Link></section></main>
}
