import { Check, Phone } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { products, cases, type Product, type CaseStudy } from '@/lib/catalog';
import { InquiryForm } from '@/components/inquiry-form';
import { getContentItems, mergeBySlug } from '@/lib/content-data';
import './home.css';
const steps=[['상담 접수','장소와 목적, 일정과 예산을 확인합니다.'],['현장 실사','벽면·전기·통신과 반입 동선을 점검합니다.'],['구성·견적','제품 규격과 공사 범위를 한 번에 제안합니다.'],['제작·설치','제작, 현장 설치와 운영 안내까지 진행합니다.']];
export default async function Home(){const catalog=mergeBySlug(products,await getContentItems<Product>('product'));const caseItems=mergeBySlug(cases,await getContentItems<CaseStudy>('case'));return <main className="design-home">
  <section className="design-hero"><div><div className="hero-tags"><span>자체 연구소 · 제조시설 보유</span><span>인천 본사 · 전국 설치</span></div><h1>모든 디스플레이,<br/>커스텀 주문 제작이<br/>가능합니다</h1><p>관공서 홍보 게시판부터 프랜차이즈 전자메뉴판까지.<br/>상담부터 설치, 유지보수까지 한 번에 진행합니다.</p><div className="design-actions"><a className="red-button" href="#quote">제품 · 견적 문의</a><Link className="soft-button" href="/cases">설치 사례 보기</Link></div></div><figure><Image unoptimized src="/oic/prod-notice.jpg" alt="오아이씨코리아 안내전광판" width={600} height={400} priority/><figcaption>안내전광판 — 나라장터 쇼핑몰 등록 제품</figcaption></figure></section>
  <section className="proof-strip"><div><b>20년+</b><span>디스플레이 제조 업력</span></div><div><b>{caseItems.length}곳+</b><span>공개된 설치 사례</span></div><div><b>전국</b><span>현장 실사 · A/S망</span></div><div><b>A to Z</b><span>상담부터 유지보수까지</span></div></section>
  <section className="design-section"><header><h2>목적에 맞는 디스플레이를 찾으세요</h2><p>설치 장소와 사용 목적을 알려주시면 알맞은 규격과 구성을 안내해 드립니다.</p></header><div className="design-product-grid">{catalog.map(product=><Link href={`/products/${product.slug}`} key={product.slug}>{product.image&&<Image unoptimized src={product.image} alt={product.name} width={1200} height={800}/>}<div><small>{product.category}</small><h3>{product.name}</h3><p><strong>{(product.price||'상담 후 안내').replace('시안 기준 ','')}</strong></p><span>{product.status}</span></div></Link>)}</div><p className="section-note">설치비는 현장마다 다릅니다. 현장 실사 후 정확히 산출해 드립니다.</p></section>
  <section className="design-section task-section"><h2>이런 과제를 해결합니다</h2><div><Link className="task-dark" href="/business#public"><small>관공서 · 공공기관</small><h3>나라장터 가격으로 예산을 집행하고,<br/>설치는 원스톱으로 진행합니다</h3><p>구정 홍보 전자게시판, 시정 홍보 멀티비전, 방재실 비디오월을 현장에 맞춰 구성합니다.</p><b>관공서 안내 보기 →</b></Link><Link href="/business#franchise"><small>프랜차이즈 · 매장</small><h3>전자메뉴판부터 본사 통합 관리까지,<br/>전 지점을 한 번에 구축합니다</h3><p>운영 환경에 맞는 산업용 패널과 원격 콘텐츠 관리 방식을 함께 제안합니다.</p><b>프랜차이즈 안내 보기 →</b></Link></div></section>
  <section className="design-section"><header className="split-head"><h2>설치 사례</h2><Link href="/cases">더 많은 사례 보기 →</Link></header><div className="design-case-grid">{caseItems.map(item=><Link href={`/cases/${item.slug}`} key={item.slug}>{item.image&&<Image unoptimized src={item.image} alt={item.title} width={1200} height={750}/>}<small>{item.place} · {item.purpose}</small><h3>{item.title}</h3><p>{item.summary}</p></Link>)}</div></section>
  <section className="design-section process-section"><header><h2>복잡한 설치 조건도, 네 단계면 충분합니다</h2><p>전문 용어를 몰라도 괜찮습니다. 장소와 목적부터 알려주세요.</p></header><div>{steps.map((step,index)=><article key={step[0]}><b>0{index+1}</b><h3>{step[0]}</h3><p>{step[1]}</p></article>)}</div></section>
  <section className="design-quote" id="quote"><div><p className="eyebrow light">PRODUCT & PROJECT INQUIRY</p><h2>제품 · 견적 문의</h2><p>정확한 제품명을 몰라도 됩니다. 장소와 목적을 남기면 신재훈 과장이 확인합니다.</p><ul><li><Check/>제품·규격 검토</li><li><Check/>예산 범위 안내</li><li><Check/>현장 실사 여부 확인</li></ul><a href="tel:0327197947"><Phone/>032-719-7947</a></div><InquiryForm compact/></section>
</main>}
